config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save

    redirect_to flats_path(@flat)
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)

    redirect_to flats_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    redirect_to flats_path(@flat)
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container mt-3">

  <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <h3>There are <%= @flats.length%> on our website.</h3>
    </div>
  </div>
  <div class="row">
    <% @flats.each do |flat| %>
    <div class="col-xs-12 col-sm-4">
      <div class="flat-card">
        <div class="flat-card-content">
          <div class="flat-card-title">
            <h4><%= flat.name %></h3>
          </div>
          <p><%= flat.address%></p>
          <div class="flex">
            <div class="flex icon mr-2">
              <i class="fas fa-euro-sign"></i><%= flat.price_per_night%>
            </div>
            <div class="flex ml-3 icon mr-2">
              <i class="fas fa-users"></i><%= flat.number_of_guests%>
            </div>
          </div>
        </div>
        <div class="flat-card-actions">
          <a href="/flats/1158"><%= link_to "More info", flat_path(flat.id) %></a>
          <a href="#" class="ml-3 text-warning"><%= link_to "Edit", edit_flat_path(flat.id) %></a>
          <a href="#" class="ml-3 text-danger"><%= link_to "Remove", flat_path(flat.id),
                                                                     method: :delete,
                                                                      data: { confirm: "Are you sure?" } %></a>
        </div>
      </div>
    </div>
    <%end%>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Add a new Flat</h1>
        <div class="mt-3">
          <%= simple_form_for [@flat] do |f| %>
            <%= f.input :name %>
            <%= f.input :address %>
            <%= f.input :description %>
            <%= f.input :price_per_night %>
            <%= f.input :number_of_guests %>
            <%= f.submit "Add", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200')"></div>
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <p class="flat-show-address"><%=@flat.address%></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%=@flat.description%></p>
        <div class="map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=10 Clifton Gardens London W9 1DT&amp;zoom=13&amp;scale=2&amp;size=1000x1000&amp;maptype=roadmap&amp;markers=color:red%7C10 Clifton Gardens London W9 1DT&amp;key=AIzaSyBtaHK-BLhBg7TruJu8iKk_wETqZMJM-GY')"></div>
      </div>
    </div>

    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>

        <form action="">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-addon" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            <i class="fas fa-euro-sign"></i><%= @flat.price_per_night%>
          </div>
          <div class="flex ml-3">
            <i class="fas fa-users"></i><%= @flat.number_of_guests%>
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>

          <div class="flex">
            <i class="fab fa-facebook-square fa-2x mr-2"></i>
            <i class="fab fa-twitter-square fa-2x mr-2"></i>
            <i class="fab fa-pinterest-square fa-2x mr-2"></i>
            <i class="fas fa-envelope-square fa-2x"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-wagon">
      <%= link_to "Simple Airbnb", flats_path, class: "navbar-wagon-item navbar-wagon-link"%>
      <button type="button" class="btn btn-outline-primary"><%= link_to "Add Flat", new_flat_path%></button>
    </div>
    <%= yield %>
  </body>
</html>